theme: jekyll-theme-cayman
title: Consuelo Guadalupe Cuevas
email: cgc66@cornell.edu
description: >- 
  Graduate Computer Science Engineering Researcher and Software Engineer
  Concentration: Computational Perception and Robotics
github_username: conniec14

